t fixing MacOS pipeline for zsh

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -16,19 +16,20 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Ensure ${{ matrix.shell }} is installed
-        run: |
-            SHELL_CMD="${{ matrix.shell }}"
-            echo "Checking if $SHELL_CMD is installed..."
-            if ! command -v "$SHELL_CMD" &> /dev/null; then
-                echo "$SHELL_CMD not found, attempting to install..."
-                sudo apt-get update
-                sudo apt-get install -y "$SHELL_CMD"
-            else
-                echo "$SHELL_CMD is already installed."
-            fi
+        run: cat /etc/shells
+      # run: |
+        #     SHELL_CMD="${{ matrix.shell }}"
+        #     echo "Checking if $SHELL_CMD is installed..."
+        #     if ! command -v "$SHELL_CMD" &> /dev/null; then
+        #         echo "$SHELL_CMD not found, attempting to install..."
+        #         sudo apt-get update
+        #         sudo apt-get install -y "$SHELL_CMD"
+        #     else
+        #         echo "$SHELL_CMD is already installed."
+        #     fi
 
       - name: Run tool install/uninstall in ${{ matrix.shell }}
-        run: ${{ matrix.shell }} -c "./pipeline_test.sh"
+        run: ${{ matrix.shell }} -ic "./pipeline_test.sh"
 
   Ubuntu:
     name: Ubuntu ${{ matrix.version }} - ${{ matrix.shell }}
