. e enabling pipeline for MacOS and Linux

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -20,111 +20,111 @@ env:
     ENV: prod
 
 jobs:
-    # MacOS:
-    #     name: MacOS ${{ matrix.version }}
-    #     runs-on: macos-${{ matrix.version }}
-    #     strategy:
-    #         matrix:
-    #             version: [13, 14, 15]
-    #     steps:
-    #         - name: checkout repo
-    #           uses: actions/checkout@v4
+    MacOS:
+        name: MacOS ${{ matrix.version }}
+        runs-on: macos-${{ matrix.version }}
+        strategy:
+            matrix:
+                version: [13, 14, 15]
+        steps:
+            - name: checkout repo
+              uses: actions/checkout@v4
 
-    #         - name: Check runner
-    #           run: .github/scripts/AgentInfo.sh
+            - name: Check runner
+              run: .github/scripts/AgentInfo.sh
 
-    #         - name: Ensure correct SHELL availability
-    #           run: |
-    #             echo "--------Shells----------------------"
-    #             cat /etc/shells
-    #             echo "-------MacOS SW version-------------"
-    #             sw_vers
+            - name: Ensure correct SHELL availability
+              run: |
+                echo "--------Shells----------------------"
+                cat /etc/shells
+                echo "-------MacOS SW version-------------"
+                sw_vers
 
-    #         - name: zsh install tools
-    #           shell: zsh {0}
-    #           run: |
-    #             export SHELL=$(which zsh)
-    #             echo "SHELL = $SHELL"
-    #             ./test_install.sh "tools_"
+            - name: zsh install tools
+              shell: zsh {0}
+              run: |
+                export SHELL=$(which zsh)
+                echo "SHELL = $SHELL"
+                ./test_install.sh "tools_"
 
-    #         - name: zsh uninstall tools
-    #           shell: zsh {0}
-    #           run: |
-    #             export SHELL=$(which zsh)
-    #             echo "SHELL = $SHELL"
-    #             ./test_uninstall.sh "tools_"
+            - name: zsh uninstall tools
+              shell: zsh {0}
+              run: |
+                export SHELL=$(which zsh)
+                echo "SHELL = $SHELL"
+                ./test_uninstall.sh "tools_"
 
-    #         - name: bash install tools
-    #           shell: bash {0}
-    #           run: |
-    #             export SHELL=$(which bash)
-    #             echo "SHELL = $SHELL"
-    #             ./test_install.sh "tools_"
+            - name: bash install tools
+              shell: bash {0}
+              run: |
+                export SHELL=$(which bash)
+                echo "SHELL = $SHELL"
+                ./test_install.sh "tools_"
 
-    #         - name: bash uninstall tools
-    #           shell: bash {0}
-    #           run: |
-    #             export SHELL=$(which bash)
-    #             echo "SHELL = $SHELL"
-    #             ./test_uninstall.sh "tools_"
+            - name: bash uninstall tools
+              shell: bash {0}
+              run: |
+                export SHELL=$(which bash)
+                echo "SHELL = $SHELL"
+                ./test_uninstall.sh "tools_"
 
-    # Ubuntu:
-    #     name: Ubuntu ${{ matrix.version }}
-    #     runs-on: ubuntu-${{ matrix.version }}
-    #     strategy:
-    #         matrix:
-    #             version: [22.04, 24.04]
-    #     steps:
-    #         - name: checkout repo
-    #           uses: actions/checkout@v4
+    Ubuntu:
+        name: Ubuntu ${{ matrix.version }}
+        runs-on: ubuntu-${{ matrix.version }}
+        strategy:
+            matrix:
+                version: [22.04, 24.04]
+        steps:
+            - name: checkout repo
+              uses: actions/checkout@v4
 
-    #         - name: Check runner
-    #           run: .github/scripts/AgentInfo.sh
+            - name: Check runner
+              run: .github/scripts/AgentInfo.sh
 
-    #         - name: Ensure zsh is installed
-    #           run: |
-    #             SHELL_CMD="zsh"
-    #             echo "Checking if $SHELL_CMD is installed..."
-    #             if ! command -v "$SHELL_CMD" &> /dev/null; then
-    #                 echo "$SHELL_CMD not found, attempting to install..."
-    #                 sudo apt-get update
-    #                 sudo apt-get install -y "$SHELL_CMD"
-    #                 echo "$SHELL_CMD just installed."
-    #             else
-    #                 echo "$SHELL_CMD is already installed."
-    #             fi
-    #             echo "--------Shells----------------------"
-    #             cat /etc/shells
-    #             echo "--------Linux os-release------------"
-    #             cat /etc/os-release
+            - name: Ensure zsh is installed
+              run: |
+                SHELL_CMD="zsh"
+                echo "Checking if $SHELL_CMD is installed..."
+                if ! command -v "$SHELL_CMD" &> /dev/null; then
+                    echo "$SHELL_CMD not found, attempting to install..."
+                    sudo apt-get update
+                    sudo apt-get install -y "$SHELL_CMD"
+                    echo "$SHELL_CMD just installed."
+                else
+                    echo "$SHELL_CMD is already installed."
+                fi
+                echo "--------Shells----------------------"
+                cat /etc/shells
+                echo "--------Linux os-release------------"
+                cat /etc/os-release
 
-    #         - name: zsh install tools
-    #           shell: zsh {0}
-    #           run: |
-    #             export SHELL=$(which zsh)
-    #             echo "SHELL = $SHELL"
-    #             ./test_install.sh "tools_"
+            - name: zsh install tools
+              shell: zsh {0}
+              run: |
+                export SHELL=$(which zsh)
+                echo "SHELL = $SHELL"
+                ./test_install.sh "tools_"
 
-    #         - name: zsh uninstall tools
-    #           shell: zsh {0}
-    #           run: |
-    #             export SHELL=$(which zsh)
-    #             echo "SHELL = $SHELL"
-    #             ./test_uninstall.sh "tools_"
+            - name: zsh uninstall tools
+              shell: zsh {0}
+              run: |
+                export SHELL=$(which zsh)
+                echo "SHELL = $SHELL"
+                ./test_uninstall.sh "tools_"
 
-    #         - name: bash install tools
-    #           shell: bash {0}
-    #           run: |
-    #             export SHELL=$(which bash)
-    #             echo "SHELL = $SHELL"
-    #             ./test_install.sh "tools_"
+            - name: bash install tools
+              shell: bash {0}
+              run: |
+                export SHELL=$(which bash)
+                echo "SHELL = $SHELL"
+                ./test_install.sh "tools_"
 
-    #         - name: bash uninstall tools
-    #           shell: bash {0}
-    #           run: |
-    #             export SHELL=$(which bash)
-    #             echo "SHELL = $SHELL"
-    #             ./test_uninstall.sh "tools_"
+            - name: bash uninstall tools
+              shell: bash {0}
+              run: |
+                export SHELL=$(which bash)
+                echo "SHELL = $SHELL"
+                ./test_uninstall.sh "tools_"
 
     WSL:
         name: WSL Ubuntu ${{ matrix.version }}
@@ -181,18 +181,18 @@ jobs:
                 echo "SHELL = $SHELL"
                 /bin/bash ./test_uninstall.sh "wsl"
 
-    # handle-release-tags:
-    #     name: Handle Release Tags
-    #     needs: [MacOS, Ubuntu, WSL]
-    #     runs-on: ubuntu-latest
-    #     if: always() && !cancelled()  # Run whether tests pass or fail, but not if cancelled due to concurrency
-    #     steps:
-    #         - name: Checkout code
-    #           uses: actions/checkout@v4
-    #           with:
-    #             fetch-depth: 0
-    #             token: ${{ secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
-    #             persist-credentials: true
+    handle-release-tags:
+        name: Handle Release Tags
+        needs: [MacOS, Ubuntu, WSL]
+        runs-on: ubuntu-latest
+        if: always() && !cancelled()  # Run whether tests pass or fail, but not if cancelled due to concurrency
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+              with:
+                fetch-depth: 0
+                token: ${{ secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
+                persist-credentials: true
 
-    #         - name: Handle release tags
-    #           run: ./.github/scripts/handle_release_tags.sh "${{ needs.MacOS.result }}" "${{ needs.Ubuntu.result }}" "${{ needs.WSL.result }}" "${{ github.ref_name }}"
+            - name: Handle release tags
+              run: ./.github/scripts/handle_release_tags.sh "${{ needs.MacOS.result }}" "${{ needs.Ubuntu.result }}" "${{ needs.WSL.result }}" "${{ github.ref_name }}"
